app = "naoki-app"
primary_region = "cdg"

[build]
  [build.args]
    NODE_VERSION = "22"
    PHP_VERSION = "8.4"

[env]
  APP_ENV = "production"
  LOG_CHANNEL = "stderr"
  LOG_LEVEL = "info"
  LOG_STDERR_FORMATTER = "Monolog\\Formatter\\JsonFormatter"
  DB_CONNECTION = "sqlite"
  DB_DATABASE = "/data/database.sqlite"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[[mounts]]
  source = "data"
  destination = "/data"

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
